### ISSUE TITLE
Use latest anber version on recipes

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/recipes#17]
Currently recipes are using:

```yaml
dependencies:
  amber:
    github: amberframework/amber
    branch: master
    #version: {{ amber_version }}
```

Once amber v0.8.0 is released we should change this to:

```yml
dependencies:
  amber:
    github: amberframework/amber
    # branch: master
    version: {{ amber_version }}
```
