### ISSUE TITLE
Add new amber watch configuration to all recipes

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/recipes#28]
See: https://github.com/amberframework/amber/pull/865

Basically now any developer can customize the `amber watch` command tasks using `.amber.yml` file:

```yml
type: app
database: sqlite
language: slang
model: granite
watch:
  server:
    files: ["src/**/*.cr", "src/**/*.ecr"]
    command: shards build
  client:
    files: "public/**/*"
    command: ["yarn install", "yarn run watch"]
  jobs:
    files: "src/jobs/*"
    command: crystal run src/sidekiq.cr
```
